language: java
jdk:
- oraclejdk8
branches:
  only:
  - master
  - develop
notifications:
  email:
    recipients:
    - socrtx@gmail.com
services:
- mysql
before_install:
- mysql -e 'CREATE DATABASE IF NOT EXISTS karlos_test;'
script:
#Test unitario y de integracion en develop
- mvn verify --settings settings.xml
